const IDENTIFIER = 'AUTH/';

const AUTH_SUCCESS = `${IDENTIFIER}AUTH_SUCCESS`;
const AUTH_REQUEST = `${IDENTIFIER}AUTH_REQUEST`;
const AUTH_FAILURE = `${IDENTIFIER}AUTH_FAILURE`;

export {
    AUTH_SUCCESS,
    AUTH_FAILURE,
    AUTH_REQUEST
}