const IDENTIFIER = 'TRACKS/';

const types = {
  GET_ALL_TRACKS_REQUEST: `${IDENTIFIER}GET_ALL_TRACKS_REQUEST`,
  GET_ALL_TRACKS_SUCCESS: `${IDENTIFIER}GET_ALL_TRACKS_SUCCESS`,
  GET_ALL_TRACKS_FAILURE: `${IDENTIFIER}GET_ALL_TRACKS_FAILURE`,
  DEL_FOUND_TRACK: `${IDENTIFIER}DEL_FOUNDED_TRACK`,
};

export default types;