const IDENTIFIER = 'USER_PLAYLIST/'

const types = {
  ADD_TRACK: `${IDENTIFIER}ADD_TRACK`,
  DEL_TRACK: `${IDENTIFIER}DEL_TRACK`,
  SET_CURRENT_TRACK: `${IDENTIFIER}GET_CURRENT_TRACK`,
  CHANGE_CURRENT_TRACK: `${IDENTIFIER}CHANGE_CURRENT_TRACK`,
};

export default types;